### ISSUE TITLE
Century needs update to biomass libraries

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extensions-Succession#6]
To be compatible with the new harvest extensions and the land use extension, Century needs to be re-coded to be compatible with the biomass libraries.  Lesley Bross did so on a branch; needs to implemented on the trunk.

**Comment by lbross** [comment]
The code changes came from Brian M. I incorporated these into v3.2.1 originally in GoogleCode on branch /trunk/Century-succession/branches/version-LB-deploy. Recommend:
1. Move Century succession into its own GitHub project
2. I can create a GitHub branch and copy the updates into this GitHub branch (if given commit access)
3. Once the updated installer is tested, will be straightforward to merge into main

**Comment by rmscheller** [comment]
Thanks, Lesley, for the quick feedback.  GitBash isn't working on my computer here at Harvard and this might therefore need to wait until I get back to Portland in a week.  There have been some minor code changes since you created v3.2.1.  Do we start with a new branch off the trunk?

**Comment by lbross** [comment]
Yes. That is safest. In GitHub parlance after you create the new GitHub repository, we should branch off of "main". I will then copy the affected files from the version-LB-deploy branch onto the new branch. We can use the SVN log, which is still available, to identify these files. We'll need to closely examine the changes in each file to make sure we don't accidentally overwrite something else that's been changed in the last year.
